export const listdata = [
  {
    products: "Iphone 13 Pro",
    OrderId: "#11232",
    date: "Jun 29,2022",
    custname: "Afaq Karim",
    status: "Delivered",
    amount: "$400.00",
    actions: "view",
  },
  {
    products: "Mackbook Pro",
    OrderId: "#11232",
    date: "Jun 29,2022",
    custname: "Afaq Karim",
    status: "Delivered",
    amount: "$400.00",
    actions: "view",
  },
  {
    products: "Apple Watch",
    OrderId: "#11232",
    date: "Jun 29,2022",
    custname: "Afaq Karim",
    status: "Delivered",
    amount: "$400.00",
    actions: "view",
  },
  {
    products: "Microsoft Book",
    OrderId: "#11232",
    date: "Jun 29,2022",
    custname: "Afaq Karim",
    status: "Delivered",
    amount: "$400.00",
    actions: "view",
  },
  {
    products: "Apple Pen",
    OrderId: "#11232",
    date: "Jun 29,2022",
    custname: "Afaq Karim",
    status: "Delivered",
    amount: "$400.00",
    actions: "view",
  },
  {
    products: "Airpods",
    OrderId: "#11232",
    date: "Jun 29,2022",
    custname: "Afaq Karim",
    status: "Delivered",
    amount: "$400.00",
    actions: "view",
  },
];
